apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices-training
data:
  ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"
  SYSTEM_API_URL: "http://system-api:8081"
  MIDDLEWARE_URL: "http://middleware:8082"
