# Day 26 — Kubernetes Deployment for system-api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-api
  namespace: microservices-training
  labels:
    app: system-api
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: system-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: system-api
        version: "1.0.0"
    spec:
      containers:
        - name: system-api
          image: capgemini/system-api:1.0.0
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: datasource-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: ZIPKIN_URL
              value: "http://zipkin:9411/api/v2/spans"
          # Day 22 — Liveness probe
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          # Day 22 — Readiness probe
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          # Day 22 — Startup probe
          startupProbe:
            httpGet:
              path: /actuator/health/startup
              port: 8081
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
