apiVersion: v1
kind: Service
metadata:
  name: system-api
  namespace: microservices-training
spec:
  selector:
    app: system-api
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
