apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
  namespace: microservices-training
spec:
  replicas: 2
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
        - name: middleware
          image: capgemini/middleware:1.0.0
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SYSTEM_API_URL
              value: "http://system-api:8081"
            - name: ZIPKIN_URL
              value: "http://zipkin:9411/api/v2/spans"
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8082 }
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8082 }
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests: { memory: "256Mi", cpu: "250m" }
            limits:   { memory: "512Mi", cpu: "500m" }
